### ISSUE TITLE
Document how to change PE download url

### ISSUE THREAD

**Issue by ryanycoleman** [oscar-stack/oscar#16]
I managed to get it working with this modification to config/pe_build.yaml

---

pe_build:
  version: 3.0.0
  download_root: <URL>

**Comment by ToonMeynen** [comment]
Still can't get it to work.
I did 
vagrant pe-build copy /Users/toon/Downloads/puppet-enterprise-3.7.2-el-6-x86_64.tar

pe_build.yaml
---
pe_build:
  version: 3.7.2
  download_root:

vms.yaml
---
vms:
- name: master
  box: centos-64-x64-vbox4210-nocm
  roles:
  - pe-puppet-master
- name: first
  box: centos-64-x64-vbox4210-nocm
  roles:
  - pe-puppet-agent
- name: second
  box: centos-64-x64-vbox4210-nocm
  roles:
  - pe-puppet-agent

Output when I run vagrant up

`Cannot fetch installer puppet-enterprise-3.7.2-el-6-x86_64.tar.gz; no download source available.

Installers available for use:
  - puppet-enterprise-3.2.3-el-6-x86_64.tar.gz
  - puppet-enterprise-3.7.0-el-6-x86_64.tar.gz
  - puppet-enterprise-3.7.2-el-6-x86_64.tar
  - puppet-enterprise-3.7.2-el-7-x86_64.tar
The Puppet Enterprise installer puppet-enterprise-3.7.2-el-6-x86_64.tar.gz
is not available. Please set the `download_root` config option to a valid
mirror, or add the installer yourself by using the `vagrant pe-build copy`
command. Downloads for Puppet Enterprise are available for download at
https://puppetlabs.com/puppet/puppet-enterprise/`

Any suggestions?

**Comment by SydOps** [comment]
I fix it by:
```
---
pe_build:
  version: 3.7.2
  download_root: https://s3.amazonaws.com/pe-builds/released/3.7.2
```

But have issue to set variable in yaml file as below
```
---
pe_build:
  version: 3.7.2
  download_root: <%= "https://s3.amazonaws.com/pe-builds/released/#{pe_buiold.version}" %>
```
or
```
---
pe_build:
  version: 3.7.2
  download_root:  https://s3.amazonaws.com/pe-builds/released/#{pe_buiold.version}
```

Any ideas to make it work as recommend in [using YAML with variables](http://stackoverflow.com/questions/4150782/using-yaml-with-variables)
