### ISSUE TITLE
Setting a box's hostname doesn't work with vagrant-hosts

### ISSUE THREAD

**Issue by blbradley** [oscar-stack/oscar#20]
I tried setting a specific hostname, but it looks as if vagrant-hosts use the name only.

roles.yaml is the generated default.

**vms.yaml**

``` yaml
vms:
- name: master
  hostname: puppet.puppetlabs.com
  box: debian-70rc1-x64-vbox4210-nocm
  roles:
  - pe-puppet-master
- name: first
  hostname: web.puppetlabs.com
  box: debian-70rc1-x64-vbox4210-nocm
  roles:
  - pe-puppet-agent
```

**Error from agent**

```
[first] !! ERROR: Puppet Master at 'master:8140' could not be reached.
   Aborting installation as directed by answer file. Set
   'q_fail_on_unsuccessful_master_lookup' to 'n' if installation
   should continue despite communication failures.
```
