### ISSUE TITLE
WARN config_builder: The provider attribute, set on vm <hostname>, is deprecated and will be removed in an upcoming release. Use the providers attribute instead.

### ISSUE THREAD

**Issue by Xirixiz** [oscar-stack/oscar#45]
When starting a machine with Vagrant 1.7.4. the following message appears. It's only a warning for now though. Tried to modify roles.yaml, but probably code modification is necessary within the vagrant-config_builder.

---

WARN config_builder: The provider attribute, set on vm <hostname>, is deprecated and will be removed in an upcoming release. Use the providers attribute instead.

**Comment by Sharpie** [comment]
Without a specific configuration example, I can't give specific guidance. In general, the required change is to move the content of the `provider` scalar:

```yaml
provider:
  type: virtualbox
  customize: - [modifyvm, !ruby/sym id, '--memory', 1024]
```

To the providers array:

```yaml
providers:
  - type: virtualbox
    customize: - [modifyvm, !ruby/sym id, '--memory', 1024]
```
