### ISSUE TITLE
centos vagrant boxes use rsync by default which breaks oscar

### ISSUE THREAD

**Issue by jessereynolds** [oscar-stack/oscar#61]
The official centos vagrant boxes do not include the Virtualbox guest additions, so rsync is the default sync transport. A `vagrant up` will then just do an initial rsync for sync'd folders. There are a few issues with this with oscar:

1/ after downloading PE installer:

```
==> master: Running provisioner: pe_bootstrap...
==> master: bash: line 4: /vagrant/.pe_build/puppet-enterprise-2019.2.1-el-7-x86_64/puppet-enterprise-installer: No such file or directory
```

2/ after installing and trying to puppet apply master.pp:

```
==> master: Error: Could not run: Could not find file /vagrant/.pe_build/post-install/master.pp
```

The workaround at each step is to `vagrant reload master`.

I assume there's a way we can also get /vagrant to be mounted using vagrant-sshfs or nfs. Is there a recommended method of configuring this?

**Comment by jessereynolds** [comment]
Specifying `/vagrant` in the `synced_folders` array with type `sshfs` within the role definition works, eg:

```yaml
---
roles:
  pe-puppet-master:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    providers:
      - type: virtualbox
        linked_clone: true
        customize:
          - [modifyvm, !ruby/sym id, '--memory', 4048]
    provisioners:
      - {type: hosts, sync_hosts: true}
      - {type: pe_bootstrap, role: !ruby/sym master}
    synced_folders:
      - host_path: '.'
        guest_path: '/vagrant'
        type: sshfs
        disabled: false
```
